-- Custom agents generated by the pool expansion feature.
-- Shared pool: all authenticated users can read and write.

create table public.custom_agents (
  id text primary key,
  name text not null,
  abbr text not null check (char_length(abbr) <= 4),
  "group" text not null default 'custom',
  accent_color text not null,
  bg_color text not null,
  expertise_tags text[] not null default '{}',
  system_prompt text not null,
  created_by text not null,
  created_at timestamptz not null default now(),
  active boolean not null default true
);

alter table public.custom_agents enable row level security;

create policy "Authenticated users full access"
  on public.custom_agents
  for all
  using (true)
  with check (true);
